export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_COMPANY = 'SET_CURRENT_COMPANY';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const LOGOUT_CURRENT_USER = 'LOGOUT_CURRENT_USER';
export const LOGOUT_CURRENT_COMPANY = 'LOGOUT_CURRENT_COMPANY';